// ========================================
// FERAL DRUID - BiS DATA (Classic Level 60 Pre-Raid)
// DPS (Cat Form) + Restoration (Healer) - NO RAIDS!
// WITH INTEGRATED FARMING DETAILS
// ========================================

const feralDruidBiS = {
    // 🐱 FERAL DPS (CAT FORM) BiS
    dps: {
        preRaid: {
            name: "Pre-Raid BiS DPS (Level 60 - Classic)",
            nameEn: "Pre-Raid BiS DPS (Level 60 - Classic)",
            totalCost: "500-1000g (wenn vom AH gekauft)",
            totalCostEn: "500-1000g (if bought from AH)",
            totalTime: "60-100 Stunden (komplett farmen)",
            totalTimeEn: "60-100 hours (full farm)",
            items: [
                {
                    slot: "Kopf",
                    slotEn: "Head",
                    name: "Wolfshead Helm",
                    nameEn: "Wolfshead Helm",
                    source: "Leatherworking (225 skill) - Crafted",
                    sourceEn: "Leatherworking (225 skill) - Crafted",
                    stats: "+35 Attack Power in Cat Form, Equip: Shifting grants 20 Energy",
                    priority: "critical",
                    howToGet: "Auction House ODER selbst craften",
                    howToGetEn: "Auction House OR craft yourself",
                    dropChance: "N/A (Crafted)",
                    cost: "50-150g (AH) ODER 30g Materials",
                    costEn: "50-150g (AH) OR 30g Materials",
                    farmTime: "Sofort (AH) ODER 2-3h (LW leveln)",
                    farmTimeEn: "Instant (AH) OR 2-3h (level LW)",
                    farmGuide: "🔥🔥🔥 #1 MUST HAVE! OPTION 1: Buy from AH (50-150g). OPTION 2: Level Leatherworking to 225, farm materials: 20x Thick Leather (Tanaris/Hinterlands), 4x Cured Thick Leather (vendor), 2x Wildvine (plants in STV/Feralas). Without this helm, Cat DPS is 30% lower!",
                    farmGuideDe: "🔥🔥🔥 #1 PFLICHT! OPTION 1: Vom AH kaufen (50-150g). OPTION 2: Leatherworking auf 225 leveln, Materials farmen: 20x Thick Leather (Tanaris/Hinterlands), 4x Cured Thick Leather (Vendor), 2x Wildvine (Pflanzen in STV/Feralas). Ohne dieses Helm ist Cat DPS 30% niedriger!"
                },
                {
                    slot: "Hals",
                    slotEn: "Neck",
                    name: "Mark of Fordring",
                    nameEn: "Mark of Fordring",
                    source: "Quest: In Dreams (Eastern Plaguelands)",
                    sourceEn: "Quest: In Dreams (Eastern Plaguelands)",
                    stats: "+11 Strength, +10 Agility, +15 Stamina",
                    priority: "high",
                    howToGet: "Quest Reward - Garantiert!",
                    howToGetEn: "Quest Reward - Guaranteed!",
                    dropChance: "N/A (Quest)",
                    cost: "0g (Quest)",
                    costEn: "0g (Quest)",
                    farmTime: "1-2 Stunden (Questline)",
                    farmTimeEn: "1-2 hours (Quest chain)",
                    farmGuide: "✅ EASY & FREE! Start quest 'The Restless Souls' at Tirion Fordring in Eastern Plaguelands (79,63). Complete full quest chain until 'In Dreams'. Very easy quests, soloable! Guaranteed reward!",
                    farmGuideDe: "✅ EINFACH & GRATIS! Starte Quest 'The Restless Souls' bei Tirion Fordring in Eastern Plaguelands (79,63). Schließe komplette Questline ab bis 'In Dreams'. Sehr einfache Quests, solobar! Garantierter Reward!"
                },
                {
                    slot: "Schultern",
                    slotEn: "Shoulders",
                    name: "Truestrike Shoulders",
                    nameEn: "Truestrike Shoulders",
                    source: "Baron Rivendare (Stratholme)",
                    sourceEn: "Baron Rivendare (Stratholme)",
                    stats: "+18 Strength, +15 Agility, +1% Hit",
                    priority: "critical",
                    howToGet: "Stratholme Baron Run (~45 min)",
                    howToGetEn: "Stratholme Baron Run (~45 min)",
                    dropChance: "~3% (VERY RARE!)",
                    cost: "0g (Dungeon) ODER 500-1000g+ (AH if BoE)",
                    costEn: "0g (Dungeon) OR 500-1000g+ (AH if BoE)",
                    farmTime: "50-100+ Runs (RNG hell!)",
                    farmTimeEn: "50-100+ Runs (RNG hell!)",
                    farmGuide: "⚠️ VERY RARE! Farm Stratholme Baron runs. 45 min per run. Drop chance ~3%. Need 5-man group or can solo farm with good gear. +1% Hit is amazing but don't stress if it doesn't drop! Alternative: Truesilver Champion shoulders from LBRS.",
                    farmGuideDe: "⚠️ SEHR SELTEN! Farme Stratholme Baron Runs. 45 min pro Run. Drop Chance ~3%. Brauchst 5er Gruppe oder kannst solo farmen mit gutem Gear. +1% Hit ist amazing aber stress nicht wenn es nicht droppt! Alternative: Truesilver Champion Shoulders von LBRS."
                },
                {
                    slot: "Rücken",
                    slotEn: "Back",
                    name: "Cape of the Black Baron",
                    nameEn: "Cape of the Black Baron",
                    source: "Baron Rivendare (Stratholme)",
                    sourceEn: "Baron Rivendare (Stratholme)",
                    stats: "+15 Agility, +10 Stamina",
                    priority: "high",
                    howToGet: "Stratholme Baron Run",
                    howToGetEn: "Stratholme Baron Run",
                    dropChance: "~15%",
                    cost: "0g (Dungeon Drop, BoP)",
                    costEn: "0g (Dungeon Drop, BoP)",
                    farmTime: "15-30 Runs",
                    farmTimeEn: "15-30 Runs",
                    farmGuide: "Farm Stratholme Baron runs. Same boss as Truestrike Shoulders! ~15% drop chance. Much more common than shoulders. BiS Pre-Raid cloak!",
                    farmGuideDe: "Farme Stratholme Baron Runs. Selber Boss wie Truestrike Shoulders! ~15% Drop Chance. Viel häufiger als Shoulders. BiS Pre-Raid Umhang!"
                },
                {
                    slot: "Brust",
                    slotEn: "Chest",
                    name: "Cadaverous Armor",
                    nameEn: "Cadaverous Armor",
                    source: "Scholomance (Rare Spawn)",
                    sourceEn: "Scholomance (Rare Spawn)",
                    stats: "+22 Strength, +22 Agility, +12 Stamina",
                    priority: "critical",
                    howToGet: "Scholomance - Rare Spawn Boss",
                    howToGetEn: "Scholomance - Rare Spawn Boss",
                    dropChance: "Rare Spawn (~20%)",
                    cost: "0g (Dungeon) ODER 150-300g (AH, BoE)",
                    costEn: "0g (Dungeon) OR 150-300g (AH, BoE)",
                    farmTime: "20-40 Runs (Rare Spawn!)",
                    farmTimeEn: "20-40 Runs (Rare Spawn!)",
                    farmGuide: "🔥 BiS Pre-Raid Chest! Scholomance clear. Rare spawn 'Kirtonos the Herald' or 'Jandice Barov' drop this. Not guaranteed every run! BoE = check AH regularly, often cheaper than farming!",
                    farmGuideDe: "🔥 BiS Pre-Raid Brust! Scholomance clear. Rare Spawn 'Kirtonos the Herald' oder 'Jandice Barov' droppen das. Nicht garantiert jeden Run! BoE = check AH regelmäßig, oft günstiger als zu farmen!"
                },
                {
                    slot: "Armschienen",
                    slotEn: "Wrist",
                    name: "Bracers of the Eclipse",
                    nameEn: "Bracers of the Eclipse",
                    source: "Scholomance (Rare Spawn)",
                    sourceEn: "Scholomance (Rare Spawn)",
                    stats: "+9 Strength, +17 Agility, +9 Stamina",
                    priority: "medium",
                    howToGet: "Scholomance - Rare Spawn",
                    howToGetEn: "Scholomance - Rare Spawn",
                    dropChance: "Rare Spawn",
                    cost: "0g (Dungeon) ODER 80-150g (AH, BoE)",
                    costEn: "0g (Dungeon) OR 80-150g (AH, BoE)",
                    farmTime: "15-30 Runs",
                    farmTimeEn: "15-30 Runs",
                    farmGuide: "Same Scholomance runs as Cadaverous Armor! Rare spawn drops. BoE = check AH! Often cheaper than farming yourself.",
                    farmGuideDe: "Selbe Scholomance Runs wie Cadaverous Armor! Rare Spawn Drops. BoE = check AH! Oft günstiger als selbst zu farmen."
                },
                {
                    slot: "Hände",
                    slotEn: "Hands",
                    name: "Devilsaur Gauntlets",
                    nameEn: "Devilsaur Gauntlets",
                    source: "Leatherworking (300 skill) - Crafted",
                    sourceEn: "Leatherworking (300 skill) - Crafted",
                    stats: "+28 Attack Power, Set Bonus (2pc): +2% Hit",
                    priority: "critical",
                    howToGet: "Auction House (empfohlen!) ODER craften",
                    howToGetEn: "Auction House (recommended!) OR craft",
                    dropChance: "N/A (Crafted)",
                    cost: "200-350g (AH) ODER 150g Materials",
                    costEn: "200-350g (AH) OR 150g Materials",
                    farmTime: "Sofort (AH) ODER 10h+ (LW leveln + farm)",
                    farmTimeEn: "Instant (AH) OR 10h+ (LW level + farm)",
                    farmGuide: "🔥🔥🔥 MUST HAVE! OPTION 1 (fastest): Buy both pieces from AH (~400-600g total for set). OPTION 2: Level Leatherworking to 300, farm Devilsaur Leather in Un'Goro Crater (PvP zone! Many people farm this). Needs: 30x Devilsaur Leather, 40x Rugged Leather per piece. 2-Set Bonus: +2% Hit = ESSENTIAL for hit cap!",
                    farmGuideDe: "🔥🔥🔥 PFLICHT! OPTION 1 (schnellster): Kauf beide Teile vom AH (~400-600g total für Set). OPTION 2: Level Leatherworking zu 300, farme Devilsaur Leather in Un'Goro Crater (PvP Zone! Viele Leute farmen das). Braucht: 30x Devilsaur Leather, 40x Rugged Leather pro Teil. 2-Set Bonus: +2% Hit = ESSENTIAL für Hit Cap!"
                },
                {
                    slot: "Gürtel",
                    slotEn: "Waist",
                    name: "Mugger's Belt",
                    nameEn: "Mugger's Belt",
                    source: "Scholomance (BoE Drop)",
                    sourceEn: "Scholomance (BoE Drop)",
                    stats: "+15 Agility, +14 Stamina",
                    priority: "high",
                    howToGet: "Scholomance Trash ODER AH",
                    howToGetEn: "Scholomance Trash OR AH",
                    dropChance: "Random BoE",
                    cost: "50-120g (AH) ODER 0g (Dungeon)",
                    costEn: "50-120g (AH) OR 0g (Dungeon)",
                    farmTime: "10-20 Runs ODER sofort (AH)",
                    farmTimeEn: "10-20 Runs OR instant (AH)",
                    farmGuide: "BoE world drop in Scholomance from trash mobs. Check AH daily! Often cheaper than farming yourself. Farm on the side while farming other Scholomance items.",
                    farmGuideDe: "BoE World Drop in Scholomance von Trash Mobs. Check AH täglich! Oft günstiger als selbst zu farmen. Farm nebenbei während du andere Scholomance Items farmst."
                },
                {
                    slot: "Beine",
                    slotEn: "Legs",
                    name: "Devilsaur Leggings",
                    nameEn: "Devilsaur Leggings",
                    source: "Leatherworking (300 skill) - Crafted",
                    sourceEn: "Leatherworking (300 skill) - Crafted",
                    stats: "+46 Attack Power, Set Bonus (2pc): +2% Hit",
                    priority: "critical",
                    howToGet: "Auction House ODER craften",
                    howToGetEn: "Auction House OR craft",
                    dropChance: "N/A (Crafted)",
                    cost: "250-400g (AH) ODER 180g Materials",
                    costEn: "250-400g (AH) OR 180g Materials",
                    farmTime: "Sofort (AH) ODER 10h+ (farm)",
                    farmTimeEn: "Instant (AH) OR 10h+ (farm)",
                    farmGuide: "Part of Devilsaur 2-Set! See Gauntlets farming guide above. Buy BOTH pieces from AH = fastest way! 2-Set Bonus: +2% Hit = ESSENTIAL for hit cap!",
                    farmGuideDe: "Teil vom Devilsaur 2-Set! Siehe Gauntlets Farming Guide oben. Kauf BEIDE Teile vom AH = schnellster Weg! 2-Set Bonus: +2% Hit = ESSENTIAL für Hit Cap!"
                },
                {
                    slot: "Füße",
                    slotEn: "Feet",
                    name: "Boots of the Vanguard",
                    nameEn: "Boots of the Vanguard",
                    source: "Highlord Omokk (LBRS)",
                    sourceEn: "Highlord Omokk (LBRS)",
                    stats: "+14 Agility, +9 Stamina",
                    priority: "high",
                    howToGet: "LBRS - First Boss",
                    howToGetEn: "LBRS - First Boss",
                    dropChance: "~18%",
                    cost: "0g (Dungeon Drop, BoP)",
                    costEn: "0g (Dungeon Drop, BoP)",
                    farmTime: "10-20 Runs",
                    farmTimeEn: "10-20 Runs",
                    farmGuide: "Farm LBRS! First boss: Highlord Omokk. ~18% drop chance. Fast dungeon (~30 min). BiS Pre-Raid boots!",
                    farmGuideDe: "Farme LBRS! Erster Boss: Highlord Omokk. ~18% Drop Chance. Schneller Dungeon (~30 min). BiS Pre-Raid Boots!"
                },
                {
                    slot: "Ring 1",
                    slotEn: "Ring 1",
                    name: "Tarnished Elven Ring",
                    nameEn: "Tarnished Elven Ring",
                    source: "Quest: Horde Dire Maul Tribute",
                    sourceEn: "Quest: Horde Dire Maul Tribute",
                    stats: "+15 Agility, +5 Stamina",
                    priority: "critical",
                    howToGet: "Dire Maul Tribute Run (Horde only!)",
                    howToGetEn: "Dire Maul Tribute Run (Horde only!)",
                    dropChance: "N/A (Quest Reward)",
                    cost: "0g (Quest Reward)",
                    costEn: "0g (Quest Reward)",
                    farmTime: "1 Run (~30-45 min)",
                    farmTimeEn: "1 Run (~30-45 min)",
                    farmGuide: "🔥 HORDE ONLY! Do Dire Maul North Tribute Run (kill NO bosses, only Tribute chest). Start quest 'The Gordok Ogre Suit'. At end, open Tribute chest. Ring is guaranteed! Alliance Alternative: Quickstrike Ring (MC - need raid) or Don Julio's Band (BRD quest).",
                    farmGuideDe: "🔥 NUR HORDE! Mach Dire Maul North Tribute Run (töte KEINE Bosse, nur Tribute Truhe). Quest 'The Gordok Ogre Suit' starten. Am Ende Tribute Truhe öffnen. Ring ist garantiert! Allianz Alternative: Quickstrike Ring (MC - braucht Raid) oder Don Julio's Band (BRD Quest)."
                },
                {
                    slot: "Ring 2",
                    slotEn: "Ring 2",
                    name: "Painweaver Band",
                    nameEn: "Painweaver Band",
                    source: "General Drakkisath (UBRS)",
                    sourceEn: "General Drakkisath (UBRS)",
                    stats: "+11 Agility, +9 Stamina, +28 Attack Power",
                    priority: "high",
                    howToGet: "UBRS - General Drakkisath",
                    howToGetEn: "UBRS - General Drakkisath",
                    dropChance: "~15%",
                    cost: "0g (Dungeon Drop, BoP)",
                    costEn: "0g (Dungeon Drop, BoP)",
                    farmTime: "10-25 Runs",
                    farmTimeEn: "10-25 Runs",
                    farmGuide: "Farm UBRS! Last boss: General Drakkisath. ~15% drop chance. Same boss drops Blackhand's Breadth (BiS trinket) = farm until you get BOTH!",
                    farmGuideDe: "Farme UBRS! Endboss: General Drakkisath. ~15% Drop Chance. Selber Boss droppt Blackhand's Breadth (BiS Trinket) = farm bis du BEIDE hast!"
                },
                {
                    slot: "Trinket 1",
                    slotEn: "Trinket 1",
                    name: "Hand of Justice",
                    nameEn: "Hand of Justice",
                    source: "Emperor Dagran Thaurissan (BRD)",
                    sourceEn: "Emperor Dagran Thaurissan (BRD)",
                    stats: "Equip: +20 Attack Power, +1% Crit, Extra attack proc",
                    priority: "critical",
                    howToGet: "BRD Emperor Run",
                    howToGetEn: "BRD Emperor Run",
                    dropChance: "~5% (VERY RARE!)",
                    cost: "0g (Dungeon Drop, BoP)",
                    costEn: "0g (Dungeon Drop, BoP)",
                    farmTime: "20-50+ Runs",
                    farmTimeEn: "20-50+ Runs",
                    farmGuide: "🔥🔥🔥 #1 BiS TRINKET! Farm Blackrock Depths Emperor runs. Start at Shadowforge City, run to Throne Room. ~5% drop chance = VERY RARE! Extra attack proc = HUGE DPS increase. Farm until you get it!",
                    farmGuideDe: "🔥🔥🔥 #1 BiS TRINKET! Farme Blackrock Depths Emperor Runs. Start bei Shadowforge City, lauf zum Throne Room. ~5% Drop Chance = SEHR SELTEN! Extra Attack Proc = HUGE DPS increase. Farm bis du es hast!"
                },
                {
                    slot: "Trinket 2",
                    slotEn: "Trinket 2",
                    name: "Blackhand's Breadth",
                    nameEn: "Blackhand's Breadth",
                    source: "General Drakkisath (UBRS)",
                    sourceEn: "General Drakkisath (UBRS)",
                    stats: "Equip: +2% Crit",
                    priority: "critical",
                    howToGet: "UBRS - General Drakkisath",
                    howToGetEn: "UBRS - General Drakkisath",
                    dropChance: "~15%",
                    cost: "0g (Dungeon Drop, BoP)",
                    costEn: "0g (Dungeon Drop, BoP)",
                    farmTime: "5-15 Runs",
                    farmTimeEn: "5-15 Runs",
                    farmGuide: "🔥 #2 BiS TRINKET! Farm UBRS! Same boss as Painweaver Band ring. ~15% drop chance. +2% Crit = MASSIVE DPS! Farm UBRS until you get ring + trinket!",
                    farmGuideDe: "🔥 #2 BiS TRINKET! Farme UBRS! Selber Boss wie Painweaver Band Ring. ~15% Drop Chance. +2% Crit = MASSIVE DPS! Farm UBRS bis du Ring + Trinket hast!"
                },
                {
                    slot: "Waffe",
                    slotEn: "Weapon",
                    name: "Manual Crowd Pummeler",
                    nameEn: "Manual Crowd Pummeler",
                    source: "Crowd Pummeler 9-60 (Gnomeregan)",
                    sourceEn: "Crowd Pummeler 9-60 (Gnomeregan)",
                    stats: "Use: +50% Attack Speed for 30 sec (3 charges)",
                    priority: "critical",
                    howToGet: "Gnomeregan - Crowd Pummeler 9-60 Boss",
                    howToGetEn: "Gnomeregan - Crowd Pummeler 9-60 Boss",
                    dropChance: "~12%",
                    cost: "0g (Dungeon Drop, NOT BoE!)",
                    costEn: "0g (Dungeon Drop, NOT BoE!)",
                    farmTime: "30+ Runs - FARM VIELE!",
                    farmTimeEn: "30+ Runs - FARM MANY!",
                    farmGuide: "🔥🔥🔥 #1 BiS DPS WEAPON! Farm Gnomeregan! Boss 'Crowd Pummeler 9-60' after Dark Iron Ambassador. ~12% drop. ONLY 3 CHARGES = consumable! Farm 20-30 pieces! Use 1 per raid boss! ~15-20 min per Gnome run. NOT BoE = cannot buy! +50% attack speed = INSANE DPS!",
                    farmGuideDe: "🔥🔥🔥 #1 BiS DPS WAFFE! Farme Gnomeregan! Boss 'Crowd Pummeler 9-60' nach Dark Iron Ambassador. ~12% Drop. NUR 3 CHARGES = verbraucht sich! Farm 20-30 Stück! Use 1 per Raid Boss! ~15-20 min pro Gnome Run. NICHT BoE = kannst nicht kaufen! +50% Attack Speed = INSANE DPS!"
                },
                {
                    slot: "Idol",
                    slotEn: "Idol",
                    name: "Idol of Ferocity",
                    nameEn: "Idol of Ferocity",
                    source: "Quest: Stormers and Rumblers (Silithus)",
                    sourceEn: "Quest: Stormers and Rumblers (Silithus)",
                    stats: "Increases Cat Form attack power by 40",
                    priority: "high",
                    howToGet: "Quest in Silithus",
                    howToGetEn: "Quest in Silithus",
                    dropChance: "N/A (Quest)",
                    cost: "0g (Quest Reward)",
                    costEn: "0g (Quest Reward)",
                    farmTime: "30-45 min (Quest)",
                    farmTimeEn: "30-45 min (Quest)",
                    farmGuide: "✅ EASY! Quest 'Stormers and Rumblers' in Silithus (Cenarion Hold). Kill Dust Stormers (Air Elementals) until you have 10x Twilight Cultist Ring of Lordship. Very easy! Guaranteed reward!",
                    farmGuideDe: "✅ EINFACH! Quest 'Stormers and Rumblers' in Silithus (Cenarion Hold). Kill Dust Stormers (Air Elementals) bis du 10x Twilight Cultist Ring of Lordship hast. Sehr einfach! Garantierter Reward!"
                }
            ],
            totalStats: "+350 Attack Power, +150 Agility, +100 Stamina (ohne Verzauberungen)",
            setBonus: "Devilsaur 2-Set: +2% Hit (Hands + Legs)",
            notes: "🔥 Wolfshead Helm + Manual Crowd Pummeler = ABSOLUTE MUST HAVE! Farm 20-30 MCPs! Keine Raids nötig!"
        }
    },

    // 🌿 RESTORATION HEALER BiS
    healer: {
        preRaid: {
            name: "Pre-Raid BiS Healer (Level 60 - Classic)",
            nameEn: "Pre-Raid BiS Healer (Level 60 - Classic)",
            totalCost: "200-400g (wenn vom AH gekauft)",
            totalCostEn: "200-400g (if bought from AH)",
            totalTime: "40-60 Stunden (komplett farmen)",
            totalTimeEn: "40-60 hours (full farm)",
            items: [
                {
                    slot: "Kopf",
                    slotEn: "Head",
                    name: "Dreamweave Circlet",
                    nameEn: "Dreamweave Circlet",
                    source: "Schneiderei (300 skill) - Crafted",
                    sourceEn: "Tailoring (300 skill) - Crafted",
                    stats: "+14 Intellect, +12 Spirit, +22 Healing",
                    priority: "high",
                    howToGet: "Auction House ODER craften",
                    howToGetEn: "Auction House OR craft",
                    dropChance: "N/A (Crafted)",
                    cost: "80-150g (AH) ODER 50g Materials",
                    costEn: "80-150g (AH) OR 50g Materials",
                    farmTime: "Sofort (AH) ODER 2h (craft)",
                    farmTimeEn: "Instant (AH) OR 2h (craft)",
                    farmGuide: "Buy from AH (cheapest!) OR craft with Tailoring 300. Materials: Dreamweave, Felcloth. Good Pre-Raid head!",
                    farmGuideDe: "Vom AH kaufen (günstigster!) ODER mit Schneiderei 300 craften. Materialien: Dreamweave, Felcloth. Gutes Pre-Raid Helm!"
                },
                {
                    slot: "Hals",
                    slotEn: "Neck",
                    name: "Animated Chain Necklace",
                    nameEn: "Animated Chain Necklace",
                    source: "Ramstein (Stratholme)",
                    sourceEn: "Ramstein (Stratholme)",
                    stats: "+12 Intellect, +8 Spirit, +31 Healing",
                    priority: "critical",
                    howToGet: "Stratholme - Boss vor Baron",
                    howToGetEn: "Stratholme - Boss before Baron",
                    dropChance: "~18%",
                    cost: "0g (Dungeon Drop, BoP)",
                    costEn: "0g (Dungeon Drop, BoP)",
                    farmTime: "10-15 Runs",
                    farmTimeEn: "10-15 Runs",
                    farmGuide: "🔥 BiS Pre-Raid Neck! Farm Stratholme! Boss: Ramstein the Gorger (before Baron). ~18% drop chance. +31 Healing = HUGE!",
                    farmGuideDe: "🔥 BiS Pre-Raid Hals! Farme Stratholme! Boss: Ramstein the Gorger (vor Baron). ~18% Drop Chance. +31 Healing = HUGE!"
                },
                {
                    slot: "Schultern",
                    slotEn: "Shoulders",
                    name: "Mantle of the Lost Tribe",
                    nameEn: "Mantle of the Lost Tribe",
                    source: "Zul'Farrak (Rare BoE)",
                    sourceEn: "Zul'Farrak (Rare BoE)",
                    stats: "+11 Intellect, +13 Spirit, +33 Healing",
                    priority: "high",
                    howToGet: "Zul'Farrak ODER AH",
                    howToGetEn: "Zul'Farrak OR AH",
                    dropChance: "Rare BoE",
                    cost: "0g (Dungeon) ODER 100-200g (AH)",
                    costEn: "0g (Dungeon) OR 100-200g (AH)",
                    farmTime: "20-40 Runs ODER sofort (AH)",
                    farmTimeEn: "20-40 Runs OR instant (AH)",
                    farmGuide: "BoE rare drop from Zul'Farrak. Check AH daily! Often available. +33 Healing = BiS Pre-Raid shoulders!",
                    farmGuideDe: "BoE Rare Drop von Zul'Farrak. Check AH täglich! Oft verfügbar. +33 Healing = BiS Pre-Raid Schultern!"
                },
                {
                    slot: "Rücken",
                    slotEn: "Back",
                    name: "Drape of Benediction",
                    nameEn: "Drape of Benediction",
                    source: "Jandice Barov (Scholomance)",
                    sourceEn: "Jandice Barov (Scholomance)",
                    stats: "+11 Intellect, +10 Spirit, +22 Healing",
                    priority: "high",
                    howToGet: "Scholomance - Boss",
                    howToGetEn: "Scholomance - Boss",
                    dropChance: "~18%",
                    cost: "0g (Dungeon Drop, BoP)",
                    costEn: "0g (Dungeon Drop, BoP)",
                    farmTime: "10-15 Runs",
                    farmTimeEn: "10-15 Runs",
                    farmGuide: "Farm Scholomance! Boss: Jandice Barov (Illusionist). ~18% drop chance. BiS Pre-Raid cloak!",
                    farmGuideDe: "Farme Scholomance! Boss: Jandice Barov (Illusionistin). ~18% Drop Chance. BiS Pre-Raid Umhang!"
                },
                {
                    slot: "Brust",
                    slotEn: "Chest",
                    name: "Robes of the Exalted",
                    nameEn: "Robes of the Exalted",
                    source: "Argent Dawn - Exalted",
                    sourceEn: "Argent Dawn - Exalted",
                    stats: "+18 Intellect, +17 Spirit, +44 Healing",
                    priority: "critical",
                    howToGet: "Argent Dawn Reputation Exalted",
                    howToGetEn: "Argent Dawn Reputation Exalted",
                    dropChance: "N/A (Vendor)",
                    cost: "~50g (Vendor) + Rep Grind",
                    costEn: "~50g (Vendor) + Rep Grind",
                    farmTime: "30-40 Dungeon Runs (Rep Grind)",
                    farmTimeEn: "30-40 Dungeon Runs (Rep Grind)",
                    farmGuide: "🔥🔥🔥 #1 BiS Pre-Raid Chest! Farm Argent Dawn reputation to Exalted! Run Stratholme + Scholomance with AD trinket. Complete all Plaguelands quests. Turn in Scourgestones. Buy from AD Quartermaster at Exalted. +44 Healing = INSANE!",
                    farmGuideDe: "🔥🔥🔥 #1 BiS Pre-Raid Brust! Farme Argent Dawn Reputation bis Exalted! Lauf Stratholme + Scholomance mit AD Trinket. Schließe alle Plaguelands Quests ab. Turn in Scourgestones. Kauf von AD Quartermaster bei Exalted. +44 Healing = INSANE!"
                },
                {
                    slot: "Armschienen",
                    slotEn: "Wrist",
                    name: "Sublime Wristguards",
                    nameEn: "Sublime Wristguards",
                    source: "Dire Maul Tribute Run",
                    sourceEn: "Dire Maul Tribute Run",
                    stats: "+14 Intellect, +7 Stamina, +24 Healing",
                    priority: "high",
                    howToGet: "Dire Maul North Tribute",
                    howToGetEn: "Dire Maul North Tribute",
                    dropChance: "~25%",
                    cost: "0g (Dungeon)",
                    costEn: "0g (Dungeon)",
                    farmTime: "4-8 Runs",
                    farmTimeEn: "4-8 Runs",
                    farmGuide: "Dire Maul North Tribute Run (~30-45 min). Kill NO bosses! Run to Tribute chest. ~25% drop chance. Easy to farm!",
                    farmGuideDe: "Dire Maul Nord Tribute Run (~30-45 min). Töte KEINE Bosse! Lauf zur Tribute Truhe. ~25% Drop Chance. Einfach zu farmen!"
                },
                {
                    slot: "Hände",
                    slotEn: "Hands",
                    name: "Hands of the Exalted Herald",
                    nameEn: "Hands of the Exalted Herald",
                    source: "Princess Theradras (Maraudon)",
                    sourceEn: "Princess Theradras (Maraudon)",
                    stats: "+13 Intellect, +11 Spirit, +40 Healing",
                    priority: "critical",
                    howToGet: "Maraudon - Last Boss",
                    howToGetEn: "Maraudon - Last Boss",
                    dropChance: "~15%",
                    cost: "0g (Dungeon Drop, BoP)",
                    costEn: "0g (Dungeon Drop, BoP)",
                    farmTime: "10-20 Runs",
                    farmTimeEn: "10-20 Runs",
                    farmGuide: "🔥 BiS Pre-Raid Gloves! Farm Maraudon! Last boss: Princess Theradras. ~15% drop chance. +40 Healing = HUGE! ~30-45 min per run.",
                    farmGuideDe: "🔥 BiS Pre-Raid Handschuhe! Farme Maraudon! Endboss: Princess Theradras. ~15% Drop Chance. +40 Healing = HUGE! ~30-45 min pro Run."
                },
                {
                    slot: "Gürtel",
                    slotEn: "Waist",
                    name: "Whipvine Cord",
                    nameEn: "Whipvine Cord",
                    source: "Alzzin the Wildshaper (Dire Maul East)",
                    sourceEn: "Alzzin the Wildshaper (Dire Maul East)",
                    stats: "+13 Intellect, +12 Spirit, +22 Healing",
                    priority: "high",
                    howToGet: "Dire Maul East - Boss",
                    howToGetEn: "Dire Maul East - Boss",
                    dropChance: "~20%",
                    cost: "0g (Dungeon Drop, BoP)",
                    costEn: "0g (Dungeon Drop, BoP)",
                    farmTime: "10-15 Runs",
                    farmTimeEn: "10-15 Runs",
                    farmGuide: "Farm Dire Maul East! Boss: Alzzin the Wildshaper. ~20% drop chance. BiS Pre-Raid belt!",
                    farmGuideDe: "Farme Dire Maul East! Boss: Alzzin the Wildshaper. ~20% Drop Chance. BiS Pre-Raid Gürtel!"
                },
                {
                    slot: "Beine",
                    slotEn: "Legs",
                    name: "Padre's Trousers",
                    nameEn: "Padre's Trousers",
                    source: "Stratholme (BoE Drop)",
                    sourceEn: "Stratholme (BoE Drop)",
                    stats: "+16 Intellect, +14 Spirit, +35 Healing",
                    priority: "high",
                    howToGet: "Stratholme ODER AH",
                    howToGetEn: "Stratholme OR AH",
                    dropChance: "Random BoE",
                    cost: "0g (Dungeon) ODER 150-300g (AH)",
                    costEn: "0g (Dungeon) OR 150-300g (AH)",
                    farmTime: "20-30 Runs ODER sofort (AH)",
                    farmTimeEn: "20-30 Runs OR instant (AH)",
                    farmGuide: "BoE drop from Stratholme. Check AH daily! Often available. BiS Pre-Raid legs! +35 Healing!",
                    farmGuideDe: "BoE Drop von Stratholme. Check AH täglich! Oft verfügbar. BiS Pre-Raid Beine! +35 Healing!"
                },
                {
                    slot: "Füße",
                    slotEn: "Feet",
                    name: "Boots of Pure Thought",
                    nameEn: "Boots of Pure Thought",
                    source: "Baron Rivendare (Stratholme)",
                    sourceEn: "Baron Rivendare (Stratholme)",
                    stats: "+13 Intellect, +12 Spirit, +7 Stamina",
                    priority: "medium",
                    howToGet: "Stratholme Baron Run",
                    howToGetEn: "Stratholme Baron Run",
                    dropChance: "~8%",
                    cost: "0g (Dungeon Drop, BoP)",
                    costEn: "0g (Dungeon Drop, BoP)",
                    farmTime: "25-50 Runs",
                    farmTimeEn: "25-50 Runs",
                    farmGuide: "Farm Stratholme Baron runs (~45 min per run). Drop chance ~8%. Good Pre-Raid boots!",
                    farmGuideDe: "Farme Stratholme Baron Runs (~45 min pro Run). Drop Chance ~8%. Gute Pre-Raid Boots!"
                },
                {
                    slot: "Ring 1",
                    slotEn: "Ring 1",
                    name: "Cauterizing Band",
                    nameEn: "Cauterizing Band",
                    source: "Dire Maul Tribute (Rare)",
                    sourceEn: "Dire Maul Tribute (Rare)",
                    stats: "+10 Intellect, +9 Spirit, +20 Healing",
                    priority: "critical",
                    howToGet: "Dire Maul North Tribute",
                    howToGetEn: "Dire Maul North Tribute",
                    dropChance: "~15%",
                    cost: "0g (Dungeon)",
                    costEn: "0g (Dungeon)",
                    farmTime: "10-20 Runs",
                    farmTimeEn: "10-20 Runs",
                    farmGuide: "🔥 BiS Pre-Raid Ring! Dire Maul North Tribute Run. Kill NO bosses! Open tribute chests. ~15% drop. +20 Healing!",
                    farmGuideDe: "🔥 BiS Pre-Raid Ring! Dire Maul Nord Tribute Run. Töte KEINE Bosse! Öffne Tribute Truhen. ~15% Drop. +20 Healing!"
                },
                {
                    slot: "Ring 2",
                    slotEn: "Ring 2",
                    name: "لطف of Purity",
                    nameEn: "Band of Purity",
                    source: "Quest: Mara Scepter Questline",
                    sourceEn: "Quest: Mara Scepter Questline",
                    stats: "+11 Intellect, +8 Spirit, +24 Healing",
                    priority: "high",
                    howToGet: "Maraudon Quest",
                    howToGetEn: "Maraudon Quest",
                    dropChance: "N/A (Quest)",
                    cost: "0g (Quest Reward)",
                    costEn: "0g (Quest Reward)",
                    farmTime: "Quest chain + 1 Mara run",
                    farmTimeEn: "Quest chain + 1 Mara run",
                    farmGuide: "✅ EASY! Complete Maraudon Scepter quest chain. Guaranteed reward! +24 Healing = solid ring!",
                    farmGuideDe: "✅ EINFACH! Schließe Maraudon Scepter Quest Chain ab. Garantierter Reward! +24 Healing = solider Ring!"
                },
                {
                    slot: "Trinket 1",
                    slotEn: "Trinket 1",
                    name: "Second Wind",
                    nameEn: "Second Wind",
                    source: "Quest: Druid Epic Flight Form",
                    sourceEn: "Quest: Druid Epic Flight Form",
                    stats: "Use: +300 Mana (5 min CD)",
                    priority: "critical",
                    howToGet: "Druid Epic Quest",
                    howToGetEn: "Druid Epic Quest",
                    dropChance: "N/A (Quest)",
                    cost: "0g (Quest)",
                    costEn: "0g (Quest)",
                    farmTime: "Long quest chain",
                    farmTimeEn: "Long quest chain",
                    farmGuide: "🔥 BiS Trinket! Complete Druid Epic Flight Form quest chain. Guaranteed reward! +300 Mana on use = HUGE!",
                    farmGuideDe: "🔥 BiS Trinket! Schließe Druid Epic Flight Form Quest Chain ab. Garantierter Reward! +300 Mana on use = HUGE!"
                },
                {
                    slot: "Trinket 2",
                    slotEn: "Trinket 2",
                    name: "Briarwood Reed",
                    nameEn: "Briarwood Reed",
                    source: "Jed Runewatcher (UBRS)",
                    sourceEn: "Jed Runewatcher (UBRS)",
                    stats: "Equip: +29 Healing",
                    priority: "high",
                    howToGet: "UBRS - Boss vor General",
                    howToGetEn: "UBRS - Boss before General",
                    dropChance: "~10%",
                    cost: "0g (Dungeon Drop, BoP)",
                    costEn: "0g (Dungeon Drop, BoP)",
                    farmTime: "15-30 Runs",
                    farmTimeEn: "15-30 Runs",
                    farmGuide: "Farm UBRS! Boss: Jed Runewatcher (before General Drakkisath). ~10% drop chance. +29 Healing = solid trinket!",
                    farmGuideDe: "Farme UBRS! Boss: Jed Runewatcher (vor General Drakkisath). ~10% Drop Chance. +29 Healing = solides Trinket!"
                },
                {
                    slot: "Waffe",
                    slotEn: "Weapon",
                    name: "Hammer of Grace",
                    nameEn: "Hammer of Grace",
                    source: "Quest: Sven's Revenge (Stratholme)",
                    sourceEn: "Quest: Sven's Revenge (Stratholme)",
                    stats: "+11 Intellect, +9 Spirit, +48 Healing",
                    priority: "critical",
                    howToGet: "Stratholme Quest",
                    howToGetEn: "Stratholme Quest",
                    dropChance: "N/A (Quest)",
                    cost: "0g (Quest Reward)",
                    costEn: "0g (Quest Reward)",
                    farmTime: "Quest + 1 Stratholme run",
                    farmTimeEn: "Quest + 1 Stratholme run",
                    farmGuide: "🔥 BiS Pre-Raid Weapon! Quest: 'Sven's Revenge' in Stratholme. Guaranteed reward! +48 Healing = INSANE!",
                    farmGuideDe: "🔥 BiS Pre-Raid Waffe! Quest: 'Sven's Revenge' in Stratholme. Garantierter Reward! +48 Healing = INSANE!"
                },
                {
                    slot: "Off-Hand",
                    slotEn: "Off-Hand",
                    name: "Thaurissan's Royal Scepter",
                    nameEn: "Thaurissan's Royal Scepter",
                    source: "Emperor Dagran Thaurissan (BRD)",
                    sourceEn: "Emperor Dagran Thaurissan (BRD)",
                    stats: "+12 Intellect, +9 Spirit, +31 Healing",
                    priority: "high",
                    howToGet: "BRD Emperor Run",
                    howToGetEn: "BRD Emperor Run",
                    dropChance: "~15%",
                    cost: "0g (Dungeon Drop, BoP)",
                    costEn: "0g (Dungeon Drop, BoP)",
                    farmTime: "10-20 Runs",
                    farmTimeEn: "10-20 Runs",
                    farmGuide: "Farm BRD Emperor runs. Boss: Emperor Dagran Thaurissan. ~15% drop chance. BiS Pre-Raid off-hand!",
                    farmGuideDe: "Farme BRD Emperor Runs. Boss: Emperor Dagran Thaurissan. ~15% Drop Chance. BiS Pre-Raid Off-Hand!"
                },
                {
                    slot: "Idol",
                    slotEn: "Idol",
                    name: "Idol of Rejuvenation",
                    nameEn: "Idol of Rejuvenation",
                    source: "Quest: Mathystra Relics (Darkshore)",
                    sourceEn: "Quest: Mathystra Relics (Darkshore)",
                    stats: "Increases healing done by Rejuvenation by 50",
                    priority: "high",
                    howToGet: "Quest in Darkshore",
                    howToGetEn: "Quest in Darkshore",
                    dropChance: "N/A (Quest)",
                    cost: "0g (Quest Reward)",
                    costEn: "0g (Quest Reward)",
                    farmTime: "30-45 min (Quest)",
                    farmTimeEn: "30-45 min (Quest)",
                    farmGuide: "✅ EASY! Quest 'Mathystra Relics' in Darkshore. Collect relics from Mathystra ruins. Guaranteed reward!",
                    farmGuideDe: "✅ EINFACH! Quest 'Mathystra Relics' in Darkshore. Sammle Relics von Mathystra Ruinen. Garantierter Reward!"
                }
            ],
            totalStats: "+400 Healing Power, +200 Intellect, +150 Spirit (ohne Verzauberungen)",
            notes: "🌿 Focus auf +Healing! Robes of the Exalted = #1 Priority! Keine Raids nötig!"
        }
    }
};